name: TA-routeros - appinspect

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: TA-routeros_092.tar.gz
        uses: actions/download-artifact@v3
        with:
          path: TA-routeros_092.tar.gz
        
        
      - name: Display structure of downloaded files
        run: ls -R