name: TA-routeros - Build app

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    # outputs:
    #   app_version: ${{ steps.version_information.outputs.app_version }}
    #   build_number: ${{ steps.version_information.outputs.build_number }}
    #   artifact_name_prefix: ${{ steps.version_information.outputs.artifact_name_prefix }}
    #   tar_name: ${{ steps.version_information.outputs.tar_name }}
    #   tar_sha256: ${{ steps.XYZ.outputs.tar_name }}
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Write app version and workflow id to variables for later usage
    - name: Version information
      id: version_information
      run: |
           app_version=$(cat TA-routeros/default/app.conf | grep -o 'version =.*' | head -1 |cut -f2- -d=)
           echo "app_version=$app_version"
           echo "app_version=$app_version" >> $GITHUB_ENV
           
           build_number="${{ github.run_id }}${{ github.run_attempt }}"
           echo "build_number=$build_number" 
           echo "build_number=$build_number" >> $GITHUB_ENV

           app_version_short=$(echo $app_version | sed 's/\.//g')
           echo "app_version_short=$app_version_short"
           echo "app_version_short=$app_version_short"  >> $GITHUB_ENV

           artifact_name_prefix="TA-routeros_${app_version_short}_${build_number}"
           echo "artifact_name_prefix=$artifact_name_prefix"
           echo "artifact_name_prefix=$artifact_name_prefix" >> $GITHUB_ENV

           tar_name="TA-routeros_$app_version_short.tar.gz"
           echo "tar_name=$tar_name"
           echo "tar_name=$tar_name" >> $GITHUB_ENV

    - name: Set build number app.conf
      run: |
          ls -l TA-routeros/default/app.conf
          sed -i -e "s/replacebuild/${{ env.build_number }}/g" TA-routeros/default/app.conf
          cat TA-routeros/default/app.conf
    # run appinspect
    - name: run appinspect
      uses: VatsalJagani/splunk-app-action@v1
      with:
        app_dir: "TA-routeros"
        splunkbase_username: ${{ secrets.SPLUNKBASE_USERNAME }}
        splunkbase_password: ${{ secrets.SPLUNKBASE_PASSWORD }}

